name: ECR

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build image 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::515538249731:role/ecr-full-access
        aws-region: us-east-1

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: questionnaire-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Deploying to production server on branch $GITHUB_REF"
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ..
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      